apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - args:
        - java
        - -jar
        - front-end-0.1.0-SNAPSHOT-standalone.jar
        env:
        - name: APP_PORT
          value: "8080"
        - name: NEWSFEED_SERVICE_TOKEN
          value: T1&eWbYXNWG1w1^YGKDPxAWJ@^et^&kX
        - name: NEWSFEED_SERVICE_URL
          value: http://newsfeed:8082
        - name: QUOTE_SERVICE_URL
          value: http://quotes:8081
        - name: STATIC_URL
          value: http://static-assets:8000
        image: saiicharan/tw-infra-fe:2
        name: front-end
        ports:
        - containerPort: 8080